# _config.yml

remote_theme: "jekyll/minima" #"jekyll/minima@1fe0fbf"

title: Miscellaneous Thoughts
description: "A collection of random thoughts and ideas, both personal and academic."
baseurl: ""
markdown: kramdown
author:
  email: "alex@kiskeya.net"
  phone: +1 (917) 830-5189

minima:
  skin: solarized
  hide_site_feed_link: true
  show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

#Google Analytics ID
google_analytics: G-1WQHC00V6K

collections:
  thoughts:
    output: true
    permalink: /thoughts/:title/
  photos:
    output: true
    permalink: /photos/:title/
