# _config.yml

remote_theme: "jekyll/minima@1fe0fbf"

title: Alex Caceres-Wright
baseurl: ""
markdown: kramdown
author:
  email: "acacereswright@gmail.com"
  telephone: +1 (212) 518-4269

minima:
  skin: solarized

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
