# _config.yml

remote_theme: "jekyll/minima@1fe0fbf"

title: Miscillaneous Notes
baseurl: ""
markdown: kramdown
author:
  email: ""
  telephone: +1 (917) 830-5189

minima:
  skin: solarized

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

hide_site_feed_link: true