name: Daily Jekyll Rebuild

on:
  schedule:
    - cron: '0 5 * * *'  # Runs at 1:00 AM Eastern Time
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Make empty commit to trigger GitHub Pages rebuild
        run: |
          git commit --allow-empty -m "Daily rebuild for Jekyll posts - $(date -u)"
          git push
